### PR TITLE
feat(taskfile): Add more build tasks and rename others according to latest conventions:

### PR DESCRIPTION
**Pull request by davidlion**
- Change tasks to support building a subset of libraries through `ystdlib_LIBRARIES`.
- Add tasks for building debug and release versions.
- Add tasks for building examples.
- Rename tasks to begin with the verb.

# Description

This PR refactors the following:

* Change tasks from using wildcards to determine the target to build to using the `ystdlib_LIBRARIES` CMake variable (introduced in #65).
    * Previously, tasks could only specify an individual library/target or all libraries through a task wildcard. With the addition of the CMake variable we can now set it to support building/testing a subset of libraries.
 
* Restructures the taskfiles (and therefore namespace):
    * `:build:` -> `:ystdlib:` for tasks building/cleaning/installing ystdlib or its libraries.
    * `:test-*` -> `:test:run-*` for tasks building/running the ystdlib tests.

* Rename the following tasks to the `verb-*` pattern:
    * `deps:boost` -> `deps:install-boost`
    * `deps:Catch2` -> `deps:install-catch2`
    * `lint:cmake-check` -> `lint:check-cmake`
    * `lint:cpp-check` -> `lint:check-cpp`
    * `lint:yaml-check` -> `lint:check-yaml`
    * `lint:cmake-fix` -> `lint:fix-cmake`
    * `lint:cpp-fix` -> `lint:fix-cpp`
    * `lint:yaml-fix` -> `lint:fix-yaml`

* Migrate partially to IWYU style includes.
    * The current flattened `lint.yaml` structure breaks with multiple definitions of taskfiles, so it is left alone.
    * To support this in `deps.yaml` we bump the yscope-dev-utils submodule to pull in a fix related to `dir` usage in the boost tasks.

New features added in this PR:

* Tasks to build the examples as previously this had to be done through CMake.
* New tasks were adding to support choosing between build or release versions of ystdlib and the examples.
    * e.g. `task ystdlib:build-debug`, `task test:run-release`, `task examples:build-debug`
    * Run `task -a` for a full list.

Note for reviewer:
The diff for the changes to `ystdlib.yaml` (`build.yaml`) can be found here: https://github.com/y-scope/ystdlib-cpp/commit/e4d8ef0ec562f590ba82b3018ea71925a7a6363c. Github combines these changes with the move/rename making it appear completely new.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

New tasks tested manually and passing in CI.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

* **New Features**
  * Added new Taskfiles for building, testing, and managing the standard library and examples, supporting debug/release modes and selective builds.
  * Introduced streamlined commands for building, installing, and testing via Task, including specifying subsets of libraries.
  * Added new requirements and improved documentation for setup and usage, including [uv] dependency.

* **Bug Fixes**
  * Updated workflow to fix compilation issues by running unit tests in debug mode only.

* **Refactor**
  * Renamed and reorganized linting and build tasks for consistency and clarity.
  * Removed deprecated and redundant Taskfiles and variables.
  * Standardized task naming conventions across Taskfiles.

* **Chores**
  * Updated GitHub Actions workflows to install new dependencies and expand test matrix.
  * Updated subproject reference for development utilities.

* **Documentation**
  * Expanded and clarified build, install, and test instructions in README files.

### CODE REVIEW

File: taskfiles/ystdlib.yaml [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+
+  install:
+    internal: true
+    vars:
+      ABSOLUTE_INSTALL_PREFIX: >-
+        {{- if osIsAbs .INSTALL_PREFIX -}}
+          {{.INSTALL_PREFIX}}
+        {{- else -}}
+          {{.USER_WORKING_DIR}}/{{.INSTALL_PREFIX}}
+        {{- end}}
```
[the remark this answers is not in the document]
Comment (davidlion) [reply taskfiles/ystdlib.yaml:119]: This is exposed through https://go-task.github.io/slim-sprig/paths.html and should perform more robust checks as it uses Go's os package. This is the same issue you raised here: https://github.com/y-scope/log-surgeon/pull/142#discussion_r2220800522

File: README.md [hunk 2]
```diff
@@ -61,23 +63,26 @@ task deps:install-all
...
 [Task](#using-task).
 
-### Using Task
+### <a id="building-using-task" />Using Task
 
-To build all targets:
+To build all libraries:
 ```shell
-task build:all
+task ystdlib:build-release
```
[the remark this answers is not in the document]
Comment (davidlion) [reply README.md:70]: Do you have a source for the "GitHub-style explicit ID"? When I tried using this syntax, it didn't work.

**Review by Bill-hbrhbr — COMMENTED** [review]
Most comments regard the repo README. While not all of my suggestions may make better sense, I think the wording can be improved. Minor comments otherwise.

File: README.md [hunk 3]
```diff
@@ -61,23 +63,26 @@ task deps:install-all
...
 ```shell
-task build:unit-test-<lib_name>
+task ystdlib:build-release ystdlib_LIBRARIES="containers;io_interface"
 ```
 
+> [!NOTE]
+> Internal dependencies of the libraries you choose will be automatically built, even if you don't
+> explicitly specify them. In the example, specifying `io_interface` automatically adds
+> `wrapped_facade_headers` to the build.
+
```
[the remark this answers is not in the document]
Comment (davidlion) [reply README.md:85]: I asked Kirk before and for now it seems better to duplicate it so if anyone only reads one section they will get the information. Maybe in the future we could have a more complex readme with a separate parameter section.

File: .github/workflows/unit-tests.yaml [hunk 4]
```diff
@@ -55,4 +58,8 @@ jobs:
           }')
           || fromJson('{}')
           }}
-        run: "task test-all"
+        # Currently unit tests rely on cassert and fail to compile in release mode.
+        run: |-
+          task test:run-debug
```
[the remark this answers is not in the document]
Comment (davidlion) [reply .github/workflows/unit-tests.yaml:63]: > Also I wonder, instead of making the `build_type` into a matrix, we can simply expand this run into `release` + `debug`. I think it saves some CI time, but it's not syntactically pretty like it is now.

Unless it becomes a significant time save, I'd prefer testing both versions from scratch to avoid accidentally implicitly reusing or relying on something from the other version.

File: .github/workflows/code-linting-checks.yaml [hunk 5]
```diff
@@ -37,6 +37,10 @@ jobs:
         shell: "bash"
         run: "npm install -g @go-task/cli"
 
+      - name: "Install uv"
+        shell: "bash"
+        run: "curl --fail --location --silent --show-error https://astral.sh/uv/install.sh | sh"
```
[the remark this answers is not in the document]
Comment (davidlion) [reply .github/workflows/code-linting-checks.yaml:42]: 0.7.10 is just the minimum tested working version. I'll fix it to the current stable version. In the future we might want to test both the minimum and current stable.

File: README.md [hunk 6]
```diff
@@ -61,23 +63,26 @@ task deps:install-all
...
-task build:all
+task ystdlib:build-release
 ```
 
-To build an executable containing all unit tests:
-```shell
-task build:unit-test-all
-```
+To build a subset of libraries, set the parameter `ystdlib_LIBRARIES` to a semicolon-separated (`;`)
+list of library names. The library names match their [directory name in src/](./src/ystdlib). For
```
[the remark this answers is not in the document]
Comment (davidlion) [reply README.md]: I refactored the ystdlib_LIBRARIES information to its own section to de-duplicate things.

However for the wording in the suggestion, that change makes it sound like the library names may not match their directory name, which would be a bug if true.

File: README.md [hunk 7]
```diff
@@ -172,5 +164,36 @@ task -a
...
+Currently, only build and install tasks in the `ystdlib:` namespace are supported.
+
+#### Using CMake
+
+Set using the `-D` flag in the generation step. For example:
+
+```shell
+cmake -S . -B ./build -Dystdlib_LIBRARIES="containers;io_interface"
+```
+
```
Comment (Bill-hbrhbr) [inline README.md:197]: Might want to add a short section for `INSTALL_PREFIX`? Even though it's very self-explanatory.

File: README.md [hunk 8]
```diff
@@ -144,4 +164,36 @@ task -a
...
+#### Using Task
+
+Set by adding it after the task name. For example:
+
+```shell
+task ystdlib:build-release ystdlib_LIBRARIES="containers;io_interface"
+```
+
+Currently, only build and install tasks in the `ystdlib:` namespace are supported.
+
```
[the remark this answers is not in the document]
Comment (Bill-hbrhbr) [reply README.md:189]: Agree

**Review by Bill-hbrhbr — APPROVED** [review]
lgtm

File: README.md [hunk 9]
```diff
@@ -52,33 +53,32 @@ git submodule update --init --recursive
...
 ```shell
 task deps:install-all
 ```
 
 ## Building
 
-The library can be built directly using [CMake](#using-cmake) or indirectly using
-[Task](#using-task).
+The library can be built via [Task](#building-using-task) or directly with
+[CMake](#building-using-cmake).
```
[the remark this answers is not in the document]
Comment (Bill-hbrhbr) [reply README.md:65]: `directly` because it's a CMake project. `Task` is not the native build tool

**Comment by davidlion** [comment]
> For title, how about: `feat(taskfile): Add taskfile support and CI for building/testing ystdlib and examples in both debug and release modes; Refactor taskfiles to align with current guidelines.`

Title updated based on discussion with Kirk and Bill.
